Check if repositories are clean or non existent

diff --git a/make_help_scripts/add_tmp_commits b/make_help_scripts/add_tmp_commits
--- a/make_help_scripts/add_tmp_commits
+++ b/make_help_scripts/add_tmp_commits
@@ -6,6 +6,23 @@ DIR="${BASH_SOURCE%/*}"
 if [[ ! -d "$DIR" ]]; then DIR="$PWD"; fi
 . "$DIR/deploy_defines" || { echo "Could not source deploy_defines script. This is needed for correct execution. Exiting!"; exit; }
 
+check_repositories () {
+  # checkout a base for defined starting point
+  cd "$base_dir" || { echo "Could not go to base dir of control.ros.org. Exiting!"; exit "$ERRCODE"; }
+  if [ -n "$(git status --porcelain)" ]; then
+    echo "control.ros.org repository has uncommitted changes, which will be deleted!"; exit 2;
+  fi
+  # check if subrepos do not exist and are no symlinks
+  for repo_name in "${!subrepo_url[@]}"; do
+    if [ -L doc/"$repo_name" ]; then
+      echo "$repo_name is a symlink, delete link or repository will be broken!"; exit 2;
+    fi
+    if [ -d doc/"$repo_name" ]; then
+      echo "$repo_name repository exists already, save your changes because it will be deleted!"; exit 2;
+    fi
+  done
+}
+
 add_sub_repositories_and_commit () {
     # checkout a base for defined starting point
     cd "$base_dir" || { echo "Could not go to base dir of control.ros.org. Exiting!"; exit "$ERRCODE"; }
@@ -37,4 +54,5 @@ add_sub_repositories_and_commit () {
     done
 }
 
+check_repositories
 add_sub_repositories_and_commit
